worker_processes auto;

events {
    worker_connections 1024;
}

http {
    # Server block for jellyfin.local
    # server {
    #     listen 80;
    #     server_name jellyfin.local;

    #     # ACME challenge for Certbot (if needed)
    #     location /.well-known/acme-challenge/ {
    #         root /var/www/certbot;
    #     }

    #     # Proxy traffic to the backend server for Jellyfin
    #     location / {
    #         proxy_pass http://192.168.10.102:8096;  # Adjust to your backend server
    #         proxy_set_header Host $host;
    #         proxy_set_header X-Real-IP $remote_addr;
    #         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #         proxy_set_header X-Forwarded-Proto $scheme;
    #     }
    # }

    # # Server block for torrent.local
    # server {
    #     listen 80;
    #     server_name torrent.local;

    #     # ACME challenge for Certbot (if needed)
    #     location /.well-known/acme-challenge/ {
    #         root /var/www/certbot;
    #     }

    #     # Proxy traffic to the backend server for Torrent
    #     location / {
    #         proxy_pass http://192.168.10.102:8080;  # Adjust to your backend server
    #         proxy_set_header Host $host;
    #         proxy_set_header X-Real-IP $remote_addr;
    #         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #         proxy_set_header X-Forwarded-Proto $scheme;
    #     }
    # }

    include /etc/nginx/conf.d/*.conf;
}
