services:       
                
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun"
    volumes:
      - ${CONFIGS_PATH}prowlarr/config:/config
      - ${CONFIGS_PATH}prowlarr/backup:/data/Backup
      - ${MEDIA_PATH}/qbittorrent_downloads:/downloads
    restart: unless-stopped
    env_file:
      - '.env'

  flaresolverr:
    image: flaresolverr/flaresolverr:v3.3.24
    container_name: flaresolverr
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun"
    restart: unless-stopped
    env_file:
      - '.env' 

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun"
    volumes:
      - ${CONFIGS_PATH}sonarr/config:/config
      - ${CONFIGS_PATH}sonarr:/data/Backup
      - ${CONFIGS_PATH}sonarr/data:/data/tvshows
      - ${MEDIA_PATH}/qbittorrent_downloads:/downloads
    restart: unless-stopped
    env_file:
      - '.env'
    
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun"
    volumes:
      - ${CONFIGS_PATH}radarr/config:/config
      - ${CONFIGS_PATH}radarr:/data/movies
      - ${CONFIGS_PATH}radarr/data:/data/Backup
      - ${MEDIA_PATH}/qbittorrent_downloads:/downloads
    restart: unless-stopped
    env_file:
      - '.env'
                                           
  lidarr:
    image: linuxserver/lidarr:latest
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun"
    container_name: lidarr
    volumes:
      - ${CONFIGS_PATH}lidarr/config:/config
      - ${CONFIGS_PATH}lidarr/data:/data/musicfolder
      - ${MEDIA_PATH}/qbittorrent_downloads:/downloads
    restart: unless-stopped
    env_file:
      - '.env'

  bazarr:
    image: linuxserver/bazarr:latest
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun"
    container_name: bazarr
    volumes:
      - ${CONFIGS_PATH}bazarr/config:/config
      - ${CONFIGS_PATH}bazarr/data:/data/musicfolder
      - ${CONFIGS_PATH}sonarr/data:/data/tvshows
      - ${CONFIGS_PATH}radarr/data:/data/movies
      - ${MEDIA_PATH}/qbittorrent_downloads:/downloads
    restart: unless-stopped
    env_file:
      - '.env'
                                                                                                               
  # readarr:
  #   image: linuxserver/readarr:develop
  #   depends_on:
  #     gluetun:
  #       condition: service_healthy
  #   network_mode: "service:gluetun"
  #   container_name: readarr
  #   hostname: readarr
  #   volumes:
  #     - ${CONFIGS_PATH}Readarr/config:/config
  #     - ${CONFIGS_PATH}readarr:/data/books
  #     - ${MEDIA_PATH}/qbittorrent_downloads:/downloads
  #   ports:
  #     - 8787:8787
  #   restart: unless-stopped
  #   env_file:
  #     - '.env'
 
  # homarr:
  #   container_name: homarr
  #   depends_on:
  #     gluetun:
  #       condition: service_healthy
  #   network_mode: "service:gluetun"
  #   image: ghcr.io/homarr-labs/homarr:latest
  #   restart: unless-stopped
  #   volumes:
  #     - ${CONFIGS_PATH}Homarr/configs:/app/data/configs
  #     - ${CONFIGS_PATH}Homarr/icons:/app/public/icons
  #     - ${CONFIGS_PATH}Homarr/data:/appdata
  #   env_file:
  #     - '.env'
     
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    devices:
      # - /dev/dri
      - /dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    group_add:
      - "109" # Change this to match your "render" host group id and remove this comment
    
    ports:
      - '8096:8096/tcp'   # Jellyfin web interface
      - '7359:7359/udp'   # Network discovery
      - '1900:1900/udp'   # DLNA port
    volumes:
      - ${CONFIGS_PATH}jellyfin/config:/config
      - ${CONFIGS_PATH}radarr:/data/Movies
      - ${CONFIGS_PATH}sonarr:/data/TVShows
      - ${CONFIGS_PATH}lidarr:/data/Music
      - ${CONFIGS_PATH}readarr:/data/Books
    environment:
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    env_file:
      - '.env'
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=info
      - TZ=Asia/Jerusalem
    ports:
      - 5055:5055
    volumes:
      - ${CONFIGS_PATH}jellyseer:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
  
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ${CONFIGS_PATH}gluetun:/gluetun  # Stores VPN configs and logs
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=openvpn
      - OPENVPN_CONFIG=/gluetun/openvpn/custom.ovpn  # Path to your OpenVPN config
      - DOT=off
      - HEALTH_VPN_DURATION_INITIAL=120s
      - FIREWALL_VPN_INPUT_PORTS="${VPN_PORT_FORWARDED}"
      - FIREWALL_OUTBOUND_SUBNETS=192.168.10.0/24
      - VPN_PORT_FORWARDING=off
    ports:
      - "8080:8080"
      - "${VPN_PORT_FORWARDED}:${VPN_PORT_FORWARDED}"
      - "${VPN_PORT_FORWARDED}:${VPN_PORT_FORWARDED}/udp"
      - "8686:8686"
      - "8989:8989"
      - "9696:9696"
      - "7575:7575"
      - "7878:7878"
      - "6767:6767"
      - "8191:8191"

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
      - ${CONFIGS_PATH}qbittorrent/config:/config
      - ${MEDIA_PATH}/qbittorrent_downloads:/downloads
    environment:
      - WEBUI_PORT=8080
    healthcheck:
      start_period: 15s
    env_file:
      - '.env'
