services:       
                
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun"
    volumes:
      - ${CONFIGS_PATH}Prowlarr/config:/config
      - prowlarr_media:/data/Backup
      - media_downloads:/downloads
    restart: unless-stopped
    env_file:
      - '.env'

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun"
    restart: unless-stopped
    env_file:
      - '.env' 

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun"
    volumes:
      - ${CONFIGS_PATH}Sonarr/config:/config
      - sonarr_media:/data/Backup
      - sonarr_media:/data/tvshows
      - media_downloads:/downloads
    restart: unless-stopped
    env_file:
      - '.env'
    
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun"
    volumes:
      - ${CONFIGS_PATH}Radarr/config:/config
      - radarr_media:/data/movies
      - radarr_media:/data/Backup
      - media_downloads:/downloads
    restart: unless-stopped
    env_file:
      - '.env'
                                           
  lidarr:
    image: linuxserver/lidarr:latest
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun"
    container_name: lidarr
    volumes:
      - ${CONFIGS_PATH}Lidarr/config:/config
      - lidarr_media:/data/musicfolder
      - media_downloads:/downloads
    restart: unless-stopped
    env_file:
      - '.env'
                                                                                                               
  # readarr:
  #   image: linuxserver/readarr:develop
  #   depends_on:
  #     gluetun:
  #       condition: service_healthy
  #   network_mode: "service:gluetun"
  #   container_name: readarr
  #   hostname: readarr
  #   volumes:
  #     - ${CONFIGS_PATH}Readarr/config:/config
  #     - readarr_media:/data/books
  #     - media_downloads:/downloads
  #   ports:
  #     - 8787:8787
  #   restart: unless-stopped
  #   env_file:
  #     - '.env'
 
  homarr:
    container_name: homarr
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun"
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - ${CONFIGS_PATH}Homarr/configs:/app/data/configs
      - ${CONFIGS_PATH}Homarr/icons:/app/public/icons
      - ${CONFIGS_PATH}Homarr/data:/data
    env_file:
      - '.env'
     
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    ports:
      - '80:8096/tcp'   # Jellyfin web interface
      - '7359:7359/udp'   # Network discovery
      - '1900:1900/udp'   # DLNA port
    volumes:
      - ${CONFIGS_PATH}Jellyfin/config:/config
      - radarr_media:/data/Movies
      - sonarr_media:/data/TVShows
      - lidarr_media:/data/Music
      - readarr_media:/data/Books
    env_file:
      - '.env'
    restart: unless-stopped
  
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN  # Required for WireGuard
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Disable IPv6 leaks
    restart: unless-stopped
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ${CONFIGS_PATH}gluetun:/gluetun  # Stores VPN configs and logs
      - /wireguard:/gluetun/wireguard  # WireGuard config folder
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_INTERFACE=wg0
      - DOT=off
      - FIREWALL_OUTBOUND_SUBNETS=192.168.10.0/24  # Allow LAN access to Web UI
      - VPN_PORT_FORWARDING=off  # Enable AirVPN port forwarding
    ports:
      - "8080:8080"  # Web UI for qBittorrent
      - "${VPN_PORT_FORWARDED}:6881" # Port for qBittorrent
      - "${VPN_PORT_FORWARDED}:6881/udp" # Port for qBittorrent
      - "8686:8686" # Lidarr
      - "8989:8989" # Sonarr
      - "9696:9696" # Prowlarr
      - "7575:7575" # Homarr
      - "7878:7878" # Radarr
      - "8191:8191" # FlareSolverr

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: "service:gluetun"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
      - ${CONFIGS_PATH}qbittorrent/config:/config
      - media_downloads:/downloads
    environment:
      - WEBUI_PORT=8080
    healthcheck:
      start_period: 15s
    env_file:
      - '.env'

volumes:
  media_downloads:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.199,rw,nfsvers=4"
      device: ":${NFS_SHARE_PATH}/downloads/"
  lidarr_media:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.199,rw,nfsvers=4"
      device: ":${NFS_SHARE_PATH}/lidarr/"
  homarr_media:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.199,rw,nfsvers=4"
      device: ":${NFS_SHARE_PATH}/homarr/"
  prowlarr_media:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.199,rw,nfsvers=4"
      device: ":${NFS_SHARE_PATH}/prowlarr/"
  sonarr_media:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.199,rw,nfsvers=4"
      device: ":${NFS_SHARE_PATH}/sonarr/"
  radarr_media:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.199,rw,nfsvers=4"
      device: ":${NFS_SHARE_PATH}/radarr/"
  readarr_media:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.10.199,rw,nfsvers=4"
      device: ":${NFS_SHARE_PATH}/readarr/"